- name: app setup
  ansible.builtin.import:
    name: common
    tasks_from: app-setup

- name: app setup
  ansible.builtin.import:
    name: common
    tasks_from: nodejs-setup

- name: app setup
  ansible.builtin.import:
    name: common
    tasks_from: mongodb-setup

- name: app setup
  ansible.builtin.import:
    name: common
    tasks_from: systemd-setup
