- name: Install golang
  ansible.builtin.package:
    name: golang
    state: present

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Change directory to /app
  command: cd /app

- name: Initialize Go module named dispatch
  command: go mod init dispatch
  args:
    chdir: /app

- name: Retrieve dependencies using go get
  command: go get
  args:
    chdir: /app

- name: Build the Go project
  command: go build
  args:
    chdir: /app

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
