- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: remove html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: nginx application setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nginx-app-setup
